package com.application.ui.navigation

object Routes {
    const val LOGIN_SCREEN = "LOGIN"
    const val HOME_SCREEN = "HOME"
    const val DETAIL_SCREEN = "DETAIL_SCREEN"
    const val STAGE_DETAIL_SCREEN = "STAGE_DETAIL_SCREEN"
    const val CAPTURE_SCREEN = "CAPTURE_SCREEN"
    const val SAMPLE_DETAIL_SCREEN = "SAMPLE_DETAIL_SCREEN"

    const val CREATE_SAMPLE_SCREEN = "CREATE_SAMPLE"
    const val CREATE_PROJECT_SCREEN = "CREATE_PROJECT_SCREEN"

    const val CREATE_FORM_SCREEN = "CREATE_FORM_SCREEN"
    const val CREATE_STAGE_SCREEN = "CREATE_STAGE_SCREEN"

    const val MODIFY_PROJECT_SCREEN = "MODIFY_PROJECT_SCREEN"
    const val MODIFY_STAGE_SCREEN = "MODIFY_STAGE_SCREEN"
    const val MODIFY_FORM_SCREEN = "MODIFY_FORM_SCREEN"

    const val QUESTIONS_SCREEN = "QUESTIONS_SCREEN"
    const val CONVERSATIONS_SCREEN = "EXPERT_CHAT_SCREEN"
    const val POST_DETAIL_SCREEN = "POST_DETAIL_SCREEN"
    const val CHAT_SCREEN = "CHAT_SCREEN"
}