package com.application.ui.navigation

object Routes {
    const val HOME_SCREEN = "HOME"
    const val LOGIN_SCREEN = "LOGIN"
    const val CAPTURE_SCREEN = "CAPTURE_SCREEN"
    const val CREATE_SAMPLE_SCREEN = "CREATE_SAMPLE"
    const val CREATE_PROJECT_SCREEN = "CREATE_PROJECT_SCREEN"
    const val DETAIL_SCREEN = "DETAIL_SCREEN"
    const val MODIFY_PROJECT_SCREEN = "MODIFY_PROJECT_SCREEN"
    const val ADD_FORM_SCREEN = "ADD_FORM_SCREEN"
    const val ADD_STAGE_SCREEN = "ADD_STAGE_SCREEN"
    const val STAGE_DETAIL_SCREEN = "STAGE_DETAIL_SCREEN"
    const val MODIFY_STAGE_SCREEN = "MODIFY_STAGE_SCREEN"
    const val MODIFY_FORM_SCREEN = "MODIFY_FORM_SCREEN"
    const val WORKERS_QUESTION_SCREEN = "WORKERS_QUESTION_SCREEN"
    const val EXPERT_CHATS_SCREEN = "EXPERT_CHATS_SCREEN"
    const val CHAT_SCREEN = "CHAT_SCREEN"


    const val SAMPLE_STACK_KEY = "SAMPLE_STACK_KEY"
    const val USER_ID_STACK_KEY = "USER_ID_STACK_KEY"
    const val PROJECT_ID_STACK_KEY = "PROJECT_ID_STACK_KEY"
    const val STAGE_ID_STACK_KEY = "STAGE_ID_STACK_KEY"
    const val FORM_ID_STACK_KEY = "FORM_ID_STACK_KEY"
    const val NEW_PROJECT_ID_STACK_KEY = "NEW_PROJECT_ID_STACK_KEY"
}