package com.application.ui.navigation

object Routes {
    const val LOGIN_SCREEN = "LOGIN"
    const val HOME_SCREEN = "HOME"
    const val DETAIL_SCREEN = "DETAIL_SCREEN"
    const val STAGE_DETAIL_SCREEN = "STAGE_DETAIL_SCREEN"
    const val CAPTURE_SCREEN = "CAPTURE_SCREEN"
    const val SAMPLE_DETAIL_SCREEN = "SAMPLE_DETAIL_SCREEN"

    const val CREATE_SAMPLE_SCREEN = "CREATE_SAMPLE"
    const val CREATE_PROJECT_SCREEN = "CREATE_PROJECT_SCREEN"

    const val CREATE_FORM_SCREEN = "ADD_FORM_SCREEN"
    const val CREATE_STAGE_SCREEN = "ADD_STAGE_SCREEN"

    const val MODIFY_PROJECT_SCREEN = "MODIFY_PROJECT_SCREEN"
    const val MODIFY_STAGE_SCREEN = "MODIFY_STAGE_SCREEN"
    const val MODIFY_FORM_SCREEN = "MODIFY_FORM_SCREEN"

    const val WORKERS_QUESTION_SCREEN = "WORKERS_QUESTION_SCREEN"
    const val EXPERT_CHATS_SCREEN = "EXPERT_CHATS_SCREEN"
    const val POST_ANSWER_SCREEN = "POST_ANSWER_SCREEN"
    const val CHAT_SCREEN = "CHAT_SCREEN"

    const val SAMPLE_STACK_KEY = "SAMPLE_STACK_KEY"
}